version: '3'

volumes:
  discord_search_bot_local_mysql_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: discord_search_bot_local_django
    depends_on:
      - mysql
      # - redis
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: /start

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASS=pass
      - MYSQL_DATABASE=discord_search_bot
    volumes:
      - discord_search_bot_local_mysql_data:/var/lib/mysql

  # redis:
  #   image: redis:5.0
