# Generated by Django 2.2.9 on 2020-03-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='search_text',
            field=models.CharField(max_length=2000),
        ),
    ]
